---
- name: "Converge"
  hosts: "local"
  tasks:

    - name: "Include labocbz.add_docker_swarm"
      tags:
        - "labocbz.add_docker_swarm"
      vars:
        add_docker_swarm__is_manager: "{{ inv_add_docker_swarm__is_manager }}"
        add_docker_swarm__history_limit: "{{ inv_add_docker_swarm__history_limit }}"
        add_docker_swarm__ssl: "{{ inv_add_docker_swarm__ssl }}"
        add_docker_swarm__ssl_verify_cert: "{{ inv_add_docker_swarm__ssl_verify_cert }}"
        add_docker_swarm__ssl_path: "{{ inv_add_docker_swarm__ssl_path }}"
        add_docker_swarm__tls_name: "{{ inv_add_docker_swarm__tls_name }}"
        add_docker_swarm__ca: "{{ inv_add_docker_swarm__ca }}"
        add_docker_swarm__key: "{{ inv_add_docker_swarm__key }}"
        add_docker_swarm__cert: "{{ inv_add_docker_swarm__cert }}"
        add_docker_swarm__portainer_volume_name: "{{ inv_add_docker_swarm__portainer_volume_name }}"
        add_docker_swarm__portainer_https_port: "{{ inv_add_docker_swarm__portainer_https_port }}"
        add_docker_swarm__portainer_http_port: "{{ inv_add_docker_swarm__portainer_http_port }}"
      ansible.builtin.include_role:
        name: "labocbz.add_docker_swarm"
