---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-docker-dind"
  gather_facts: false
  tasks:

    - name: "Check the state of nodes in the cluster on Manager"
      when: inv_add_docker_swarm__is_manager | default(false)
      register: cluster_nodes
      failed_when: "'Leader' not in cluster_nodes.stdout"
      ansible.builtin.shell: |
        docker node ls

    - name: "Check the state of nodes in the cluster on Workers"
      when: not (inv_add_docker_swarm__is_manager | default(false))
      register: cluster_nodes
      failed_when: "'This node is not a swarm manager' not in cluster_nodes.stderr"
      ansible.builtin.shell: |
        docker node ls

    - name: "Check the state of services in the Portainer stack on Manager"
      when: inv_add_docker_swarm__is_manager | default(false)
      register: portainer_services
      failed_when: "'portainer' not in portainer_services.stdout"
      ansible.builtin.shell: |
        docker service ls --filter label=com.docker.stack.namespace=portainer

    - name: "Check the state of services in the Portainer stack on Workers"
      when: not (inv_add_docker_swarm__is_manager | default(false))
      register: portainer_services
      failed_when: "'This node is not a swarm manager' not in portainer_services.stderr"
      ansible.builtin.shell: |
        docker service ls --filter label=com.docker.stack.namespace=portainer

    - name: "Filter nodes by role (Manager)"
      when: inv_add_docker_swarm__is_manager | default(false)
      register: manager_nodes
      failed_when: "manager_nodes.stdout == ''"
      ansible.builtin.shell: |
        docker node ls --filter role=manager

    - name: "Filter nodes by role (Workers)"
      when: inv_add_docker_swarm__is_manager | default(false)
      register: worker_nodes
      failed_when: "worker_nodes.stdout == ''"
      ansible.builtin.shell: |
        docker node ls --filter role=worker
